server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  security:
    user:
      name: user
      password: 123456 # 固定密码，不使用security创建的用户名和变动密码（会在控制台打印）
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    lettuce:
      pool:
        max-idle: 16 # 最大空闲连接
        max-active: 32 # 最大连接数
        min-idle: 8 # 最小空闲连接
  devtools:
    restart:
      enabled: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml  # mapper的xml文件路径
  type-aliases-package: com.example.demo.domain.po # 持久化对象路径
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名，字段类型可以是boolean、integer
      logic-delete-value: 1 # 逻辑已删除值(默认为1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

#logging:
#  level:
#    com.example: debug
#  pattern:
#    dateformat: HH:mm:ss